### ISSUE TITLE
Cannot install hilldiv

### ISSUE THREAD

**Issue by marlenec** [anttonalberdi/hilldiv#2]
Hi,

Thank you for providing this super useful package ! I already used it, but had to re-install it due to a R update recently. When I tried to install the package using `devtools`, I got this error :

```
* installing *source* package ‘hilldiv’ ...
** using staged installation
** R
Error in .install_package_code_files(".", instdir) : 
files in '/private/var/folders/yj/5lcj3cvj7b32s4yfhv11gqpm0000gn/T/RtmpGWG6oZ/R.INSTALL516920653b2/hilldiv/R' missing from 'Collate' field:
  div.decomp.r
ERROR: unable to collate and parse R files for package ‘hilldiv’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/hilldiv’
Error: Failed to install 'hilldiv' from GitHub:
  (converted from warning) installation of package ‘/var/folders/yj/5lcj3cvj7b32s4yfhv11gqpm0000gn/T//RtmpBXtHZ0/file5120770d9da0/hilldiv_1.2.1.tar.gz’ had non-zero exit status
```
I looked around in the internet, and kind of understood that it could be due to bad extensions in package files ([https://stackoverflow.com/questions/14728326/files-in-collate-field-missing-from-package-when-installing-from-github](here)).
Did you already have that kind of problem with your package?

Thank you in advance!

**Comment by anttonalberdi** [comment]
Dear marlenec. Sorry for the late answer. I committed an update incorrectly and consequently it was impossible to install hilldiv for a few days, but the problem was solved a few days after your message.

**Comment by marlenec** [comment]
Dear Dr Alberdi, 

Thank you for your answer ! However I retried today and still got an error message :

* installing *source* package ‘hilldiv’ ...
** using staged installation
** R
Error in parse(outFile) : 
  /private/var/folders/yj/5lcj3cvj7b32s4yfhv11gqpm0000gn/T/Rtmps0Kp4u/R.INSTALL7af42676f1ee/hilldiv/R/pair.dis.r:11:32: unexpected input
10: if(qvalue < 0) stop("q value needs to be possitive (equal or higher than zero)")
11: if (qvalue==1) {qvalue=0.99999}\
                                   ^
ERROR: unable to collate and parse R files for package ‘hilldiv’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/hilldiv’
Error: Failed to install 'hilldiv' from GitHub:
  (converted from warning) installation of package ‘/var/folders/yj/5lcj3cvj7b32s4yfhv11gqpm0000gn/T//RtmpWAmnrw/file3ac1666349e3/hilldiv_1.2.3.tar.gz’ had non-zero exit status


Thank you in advance,

Marlène
-----------------------------------------------
Dr Marlène Chiarello
Dpt of Biology
University of Mississippi
Oxford MS, 38655
USA
Cell (France): +33 (0)6-72-13-72-12
Cell (USA): +1 (662) 202-7433

**Comment by anttonalberdi** [comment]
I'm really sorry. I apparently wrote a damm slash where I shouldn't when updating a script yesterday... It should work now. Sorry!

**Comment by marlenec** [comment]
I just retried, and it worked !

Thank you so much !

Marlene

-----------------------------------------------
Dr Marlène Chiarello
Dpt of Biology
University of Mississippi
Oxford MS, 38655
USA
Cell (France): +33 (0)6-72-13-72-12
Cell (USA): +1 (662) 202-7433

**Comment by anttonalberdi** [comment]
So glad to hear that. Please, don't hesitate to contact me if you need any help or you find out something is not working correctly.
