### ISSUE TITLE
Outdated function names in wiki

### ISSUE THREAD

**Issue by zachary-foster** [anttonalberdi/hilldiv#6]
https://github.com/anttonalberdi/hilldiv/wiki/0.-Hill-numbers#phylogenetic-indices-and-hill-numbers

https://github.com/anttonalberdi/hilldiv/wiki/3.1-Diversity-computation-of-a-single-system#hill-numbers-vs-diversity-indices

`tree.depth` -> `tree_depth`

https://github.com/anttonalberdi/hilldiv/wiki/3.2-Diversity-computation-and-comparison-of-multiple-systems#post-hoc-analyses

`div.test` -> `div_test`

I would normally just submit a PR, but I don't know how to for the wiki section.

**Comment by anttonalberdi** [comment]
Thanks for the heads up Zachary. I will update the documentation asao.
